[package]
name = "rquant"
version = "0.1.0"
edition = "2021"

[lib]
name = "rquant"
path = "src/lib.rs"

[[bin]]
name = "rquant_bin"
path = "src/main.rs"

[dependencies]
autograd = { path = "rust-autograd/", features = ["blas", "accelerate"] }
